config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{ |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_filter :require_login, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    flash.notice = "Article '#{@article.title}' Updated"

    redirect_to articles_path(@article)
  end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: "Logged in successfully.")
    else
      flash.now.alert = "Login failed."
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_author_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end

    def zero_author_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
  before_filter :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save

    redirect_to article_path(@comment.article)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, only: [:destroy]
  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading"><%= comment.author_name %>
      <small>Posted <%= distance_of_time_in_words(comment.created_at, Time.now) %> early</small>
    </h4>
    <%= comment.body %>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="well">

  <%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <div class="form-group">
    <%= f.label :tag_list %><br />
    <%= f.text_area :tag_list, class: "form-control", rows: "1" %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_area :title, class: "form-control", rows: "1" %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br />
    <%= f.text_area :body, class: "form-control", rows: "10"  %>
  </div>
  <div class="form-group">
    <% if @article.image.exists? %>
    <%= image_tag @article.image.url %><br />
    <% end %>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </div>
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  <% end %>

</div>

app/views/articles/edit.html.erb
<h1>Edit</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<%= button_to "Create a New Article", new_article_path, method: :get, class: "btn btn-success" %>


<% @articles.each do |article| %>
  <h2>
    <%= link_to article.title, article_path(article) %>
  </h2>

  <!-- <% article.tags.each do |tag| %>
    <span class="label"><%= link_to tag.name, tag_path(tag) %></span>
  <% end %> -->

  <p><span class="glyphicon glyphicon-time"></span>
    <%= article.created_at %>
  </p>

  <hr>

  <p>
    <%= article.body[0..400] + " ..." %>
  </p>

  <%= button_to "Read More", article_path(article), method: :get, class: "btn btn-primary" %>

  <hr>
<% end %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<hr>

<p><span class="glyphicon glyphicon-time"></span>
  <%= @article.created_at %>
</p>

<p>
  <% if @article.image.exists? %>
    <%= image_tag @article.image.url %>
  <% end %>
</p>

<hr>

<p class="lead"><%= @article.body %></p>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<hr>

<% if logged_in?%>
<div class="btn-group btn-group-justified" role="group">
  <div class="btn-group" role="group">
    <%= button_to "Edit", edit_article_path(@article), method: :get, class: "btn btn-default" %>
  </div>
  <div class="btn-group" role="group">
    <%= button_to "Delete", article_path(@article),
    method: :delete,
    data: {confirm: "Really delete the article?"}, class: "btn btn-default" %>
  </div>
</div>
<% end %>

<hr>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'comments/form' %>
<%= render partial: 'articles/comment', collection: @article.comments %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>


<%= form_tag author_sessions_path, method: :post, class: "form-horizontal" do %>
  <div>
    <div class="col-sm-2">
      <%= label_tag :email %>
    </div>
    <div class="col-sm-10">
      <%= text_field_tag :email %>
    </div>
    <br />
  </div>
  <div>
    <div class="col-sm-2">
      <%= label_tag :password %>
    </div>
    <div class="col-sm-10">
      <%= password_field_tag :password %>
    </div>
    <br />
  </div>
  <div class="col-sm-2">
    <%= submit_tag "Login", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <!-- <th>Password</th>
      <th>Password confirmation</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <!-- <td><%= author.password %></td>
        <td><%= author.password_confirmation %></td> -->
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<!-- <p>
  <strong>Password:</strong>
  <%= @author.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @author.password_confirmation %>
</p> -->

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<!-- <h3>Leave a Comment</h3> -->


<div class="well">
  <h4>Leave a Comment:</h4>
  <%= form_for [ @article, @comment ] do |f| %>
    <div class="form-group">
      <%= f.label :author_name, "Your name" %><br/>
      <%= f.text_area :author_name, class: "form-control", rows: "1" %>
    </div>
    <div>
      <%= f.label :body, "Text" %><br/>
      <%= f.text_area :body, class: "form-control", rows: "3" %>
    </div>

    <%= f.submit 'Submit', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_foot.html.erb
<!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; BranLiang 2016</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

app/views/layouts/_head.html.erb
<head>
  <title>JumbostartBlog</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     <div class="container col-md-6 col-md-offset-3">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
             </button>
             <%= link_to "Home", root_path, class: "navbar-brand" %>
         </div>
         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
             <ul class="nav navbar-nav pull-right">
               <li><%= link_to "Tags", tags_path %><li>
               <% if logged_in? %>
                  <li>
                     <%= link_to "logout", logout_path %>
                  </li>
              <% else %>
                  <li>
                     <%= link_to "login", login_path %>
                  </li>
              <% end %>
             </ul>
         </div>
         <!-- /.navbar-collapse -->
     </div>
     <!-- /.container -->
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render partial: '/layouts/head' %>

  <body>
    <%= render partial: '/layouts/nav' %>
    <div class="container col-md-6 col-md-offset-3">
      <div class="row">
        <% if flash.notice %>
          <div class="alert alert-success"><%= flash.notice %></div>
        <% end %>
        
        <%= yield %>

        <%= render partial: '/layouts/foot' %>
      </div>
    </div>


  </body>
</html>

app/views/tags/index.html.erb
  <% @tags.each do |tag| %>
    <h3><%= link_to tag.name, tag_path(tag) %>  <%= link_to "delete", tag_path(tag), method: :delete %></h3>
  <% end %>

app/views/tags/show.html.erb
<h1>Article Tagged with <%= @tag.name %></h1>


  <% @tag.articles.each do |article| %>
    <h3><%= link_to article.title, article_path(article) %></h3>
  <% end %>